---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: loki
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: kbot
spec:
  chart:
    spec:
      chart: loki
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: loki
        namespace: flux-system
      version: 5.41.7
  interval: 1m0s
  values:
    loki:
      auth_enabled: false
      server:
        http_listen_port: 3100
        grpc_listen_port: 9096
      commonConfig:
        instance_addr: 127.0.0.1
        path_prefix: /tmp/loki
        replication_factor: 1
        ring:
          kvstore:
            store: inmemory
      schemaConfig:
        configs:
          - from: "2020-10-24"
            store: boltdb-shipper
            object_store: filesystem
            schema: v11
            index:
              prefix: index_
              period: 24h
      rulerConfig:
        alertmanager_url: http://localhost:9093
      storage:
         filesystem:
           chunks_directory: /tmp/loki/chunks
           rules_directory: /tmp/loki/rules
    singleBinary:
      replicas: 1
